### ISSUE TITLE
Error emitted on trivial unsat benchmark

### ISSUE THREAD

**Issue by delcypher** [abenkhadra/gosat#3]
goSAT emits an error on this simple example

```
(assert false)
```

It emits

```
,error,0.003,INF,-2
```

**Comment by abenkhadra** [comment]
nlopt complains with error code -2 because the objective function generated by your example is constant (no input variables). 
This case is now handled by evaluating the objective function once and using the returned value as a minima. Optimization using NLopt is not needed here.
