### ISSUE TITLE
gosat gives `unsat` to satisfiable benchmark

### ISSUE THREAD

**Issue by delcypher** [abenkhadra/gosat#6]
gosat reports this benchmark as unsat even though it is sat

```
(set-info :smt-lib-version 2.6)
(set-info :category "crafted")
(set-info :source |Christoph M. Wintersteiger (cwinter@microsoft.com). Randomly generated floating-point testcases.|)
; Rounding mode: to zero
; Precision: double (11/53)
; X = 1.1972111975184838161823108748649246990680694580078125p756 {+ 888160275657533 756 (4.53782e+227)}
; Y = 1.791115761572864339967736668768338859081268310546875p645 {+ 3562868649026478 645 (2.61499e+194)}
; 1.1972111975184838161823108748649246990680694580078125p756 = 1.791115761572864339967736668768338859081268310546875p645 == 0

; bres: 0
; hwf : 0

(set-logic QF_FP)
(set-info :status sat)
(define-sort FPN () (_ FloatingPoint 11 53))
(declare-fun x () FPN)
(declare-fun y () FPN)
(assert (= x (fp #b0 #b11011110011 #b0011001001111100011011101101101110111111001100111101)))
(assert (= y (fp #b0 #b11010000100 #b1100101010000110100100000000001101001110001110101110)))
(assert (= (fp.eq x y) false))
(check-sat)
(exit)
````

This is the `eq-has-solution-1355.smt2` benchmark taken from SMT-COMP's QF_FP benchmark suite.

**Comment by abenkhadra** [comment]
Solver completeness comes at a considerable cost. goSAT sacrifices completeness to gain more efficiency.  Therefore, this behavior is expected. This is discussed further in our [paper](https://blog.formallyapplied.com/docs/gosat.pdf>). 

Furthermore, we have found few instances where repeated runs of goSAT on the same SMT instance gives different results, i.e, sometimes `sat` and sometimes `unsat`. This is also expected in stochastic search in general. Our claim is that goSAT is sound (modulo implementation bugs) which means that a `sat` result given by goSAT should also be `sat` in a complete solver like `z3` and `mathsat`.

Sorry for the late replies.

**Comment by delcypher** [comment]
> Solver completeness comes at a considerable cost. goSAT sacrifices completeness to gain more efficiency. Therefore, this behavior is expected. This is discussed further in our paper.

It would be better in this case to report "unknown" and not to report "unsat" because this is unsound.
You may have a different definition of sound so here's my definition

sound - "Only truths are proved". Here the "truth" is a benchmark being "sat" or "unsat".

In gosat's case only "sat" benchmarks can be proved so in all other cases it should report "unknown".

Apart from being unsound it is also really confusing to claim to "unsat" when the solver has no idea what the real answer is.

@afd, @ccadar you might want to weigh in here.

**Comment by abenkhadra** [comment]
I agree that this can cause confusions. Some reviewers have also expressed this. I believe that an `unsat`result should be claimed only by solvers that do a complete search. Clearly, goSAT is not in this department.

Therefore, goSAT now reports either `sat` or `unknown`. This is more consistent with what users, especially in the formal community, expect from a solver. Users who wish to inspect the cause of the `unknown` result should consult a status code. Currently, we provide the status code given to us by `nlopt`.

**Comment by afd** [comment]
Hi all

On 04/01/2018 20:05, Dan Liew wrote:
>
>     Solver completeness comes at a considerable cost. goSAT sacrifices
>     completeness to gain more efficiency. Therefore, this behavior is
>     expected. This is discussed further in our paper.
>
> It would be better in this case to report "unknown" and not to report 
> "unsat" because this is unsound.
> You may have a different definition of sound so here's my definition
>
> sound - "Only truths are proved". Here the "truth" is a benchmark 
> being "sat" or "unsat".
>
> In gosat's case only "sat" benchmarks can be proved so in all other 
> cases it should report "unknown".
>
> Apart from being unsound it is also really confusing to claim to 
> "unsat" when the solver has no idea what the real answer is.
>

I see your point in general, Dan (though I have not looked personally at 
goSAT).  However, if a solver is actually openly unsound, this behaviour 
is not surprising - it is the advertised behaviour, and users of the 
solver should just ignore an "unsat" result (or use it as a heuristic if 
there is reason to believe that the solver has a decent chance of being 
correct in this case).

A

**Comment by abenkhadra** [comment]
To make this thread self-contained for future reference, some definitions are in order. We say that an SMT solver is:

- Sound, if it does not report any false positives. That is, a `sat` result reported by the solver should be indeed `sat`. It's easy to validate a `sat` result given a model (variable assignment).
- Complete, if it does not report any false negatives. That is, an `unsat` result means that a `sat` model does not exist. The solver should either establish this fact, if applicable, or die trying (with say `unknown`). 

AFAIK, these terms are common in software verification literature. That said, goSAT is sound but, unlike z3, is incomplete as advertised. The issue raised by Dan, as far as I understood, is that goSAT reports `unsat` while it should in fact report `unknown`. Our original interpretation of `unsat` was something like: a `sat` model was not found. However, users of complete SMT solvers would expect `unsat` to mean: a `sat` model does not exist. 

Therefore, and to avoid any misunderstandings, goSAT was updated to report either `sat` or `unknown`. To the majority of users, the latter should mean something like: it's not known if a `sat` model exists.

Thanks for raising this issue, Dan.
